version: '3.7'
services:
  items-app:
    build:
      context: .
    depends_on:
      - setup-localstack
    ports:
      - '3000:3000'
    environment:
      # We are setting this AWS_* variables to aws-sdk can find them
      # localstack does not care about validity of those values
      - "AWS_ACCESS_KEY_ID=dummy-key-id"
      - "AWS_SECRET_ACCESS_KEY=dummy-secret-key"
    volumes:
      - .:/home/node/app/
      - /home/node/app/node_modules/

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "~/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  setup-localstack:
    image: cgswong/aws
    command: /init-localstack.sh
    environment:
      # We are setting this AWS_* variables to aws-sdk can find them
      # localstack does not care about validity of those values
      - "AWS_ACCESS_KEY_ID=dummy-key-id"
      - "AWS_SECRET_ACCESS_KEY=dummy-secret-key"
      - "AWS_REGION=eu-central-1"
    depends_on:
      - localstack
    volumes:
      - "./scripts/init-localstack.sh:/init-localstack.sh"